name: awesome_snackbar_content
description: "Beautiful content of a snack bar and material banner."
version: 1.0.4+4
#homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  custom_sizable_text:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/types/
